package Enums;

public enum Carrera {
    ADMINISTRACION_DE_EMPRESAS,
    ENSENIANZA_DE_LA_MATEMATICA_CON_ENTORNOS_TECNOLOGICOS,
    GESTION_EN_TURISMO_SOSTENIBLE,
    GESTION_EN_TURISMO_RURAL_SOSTENIBLE,
    INGENIERIA_EN_BIOTECNOLOGIA,
    INGENIERIA_EN_COMPUTACION,
    INGENIERIA_EN_DISEÑO_INDUSTRIAL,
    ADMINISTRACION_DE_TECNOLOGIA_DE_INFORMACION,
    INGENIERIA_AGRICOLA,
    INGENIERIA_AMBIENTAL,
    INGENIERIA_AGRONEGOCIOS,
    INGENIERIA_EN_COMPUTADORES,
    INGENIERIA_EN_CONSTRUCCION,
    INGENIERIA_EN_ELECTRONICA,
    INGENIERIA_EN_PRODUCCION_INDUSTRIAL,
    INGENIERIA_EN_SEGURIDAD_LABORAL_E_HIGIENE_AMBIENTAL,
    INGENIERIA_FISICA,
    INGENIERIA_FORESTAL,
    INGENIERIA_MECATRONICA,
    INGENIERIA_EN_MANTENIMIENTO_INDUSTRIAL,
    INGENIERIA_EN_MATERIALES;

}
